# Generated by Django 3.0.7 on 2020-06-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created',
        ),
    ]
